linters:
  enable-all: true
  disable:
    - deadcode
    - exhaustruct
    - exhaustivestruct
    - gci
    - goimports
    - gofumpt
    - golint
    - ifshort
    - interfacer
    - maligned
    - nlreturn
    - nosnakecase
    - paralleltest
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    - varcheck
    - wastedassign

linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign" checks
        checks: argument,case,condition,return
  nestif:
    min-complexity: 15
  nolintlint:
    require-explanation: true
    require-specific: true
  tagliatelle:
    case:
      rules:
        json: snake

  varnamelen:
      max-distance: 10
      ignore-decls:
        - t testing.T
        - r *http.Request
        - w http.ResponseWriter

  issues:
    fix: true
    exclude-rules:
      - path: _test\.go # disable some linters for test files
        linters:
          - gocyclo
          - gosec
          - dupl
          - varnamelen
    max-issues-per-linter: 0
    max-same-issues: 0

  run:
    issues-exit-code: 1